apiVersion: v1
kind: Secret
metadata:
  name: secret-azure-devops-svc
  annotations:
    kubernetes.io/service-account.name: "azure-devops-svc"
type: kubernetes.io/service-account-token
data:
  extra: YXp1cmUtZGV2b3BzLXN2Yw==