apiVersion: v1
kind: Service
metadata:
  name: yoga-frontend-service
  namespace: yoga-ns
spec:
  selector:
    app: yoga-frontend
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30002